### ISSUE TITLE
3DS version randomly crashes on Old 3DS

### ISSUE THREAD

**Issue by gdaleigna** [AlisterT/openjazz#115]
I've done a series of tests on both my original 3DS and 3DS XL consoles and I am not able to finish a level without the system crashing ("An error occurred" screen). This is reproducible on both consoles with the last two releases (2023 and 2024). The game is very smooth and presents hardly any issues until it suddenly crashes the console. Is it worth noting that the DEMO version (found on https://www.gamebrew.org/wiki/OpenJazz_3DS) presents no issue at all. I am running the latest GOG version and am launching the .3dsx file from the homebrew launcher. 

Is this a known issue? Am I missing something in my setup? Is the port meant to be run on a N3DS system for performance sake? How can I remedy?
Thanks in advance

**Comment by carstene1ns** [comment]
I need to dust off my 3DS to investigate this...
Unfortunately crashes may happen, but if it happens in every level, this seems some general problem (e.g. memory corruption). Hopefully it is easy to reproduce for me.

**Comment by carstene1ns** [comment]
Took a bit of time to reproduce, but finally it happened.
Unfortunately looks like a race condition (renderqueue shall be cleared while active).
Since this is called by a internal SDL thread, I doubt we can do much here.
Might be worth to write a small reproducer, that can be tested easier.

```text
Thread 1 received signal SIGINT, Interrupt.
svcBreak () at /home/davem/projects/devkitpro/pacman-packages/libctru/src/libctru-2.4.1/libctru/source/svc.s:401
warning: 401	/home/davem/projects/devkitpro/pacman-packages/libctru/src/libctru-2.4.1/libctru/source/svc.s: Datei oder Verzeichnis nicht gefunden
(gdb) bt
#0  svcBreak () at /home/davem/projects/devkitpro/pacman-packages/libctru/src/libctru-2.4.1/libctru/source/svc.s:401
#1  0x001586f4 in gxCmdQueueClear (queue=0x21a9f0 <__C3D_Context>)
    at /home/davem/projects/devkitpro/pacman-packages/libctru/src/libctru-2.4.1/libctru/source/gpu/gxqueue.c:56
```
[libctru source](https://github.com/devkitPro/libctru/blob/30dc65121dc37ad5faf33ca842fd8d63f425f04f/libctru/source/gpu/gxqueue.c#L55-L56)
```text
#2  0x001539bc in C3Di_WaitAndClearQueue (timeout=-1)
    at /Users/davem/projects/devkitpro/pacman-packages/citro3d/src/citro3d-1.7.1/source/renderqueue.c:98
#3  C3Di_WaitAndClearQueue (timeout=-1)
    at /Users/davem/projects/devkitpro/pacman-packages/citro3d/src/citro3d-1.7.1/source/renderqueue.c:92
```
[citro3d source](https://github.com/devkitPro/citro3d/blob/9f21cf7b380ce6f9e01a0420f19f0763e5443ca7/source/renderqueue.c#L92-L100)
```text
#4  C3Di_SafeDisplayTransfer (flags=3, outdim=16777728, outadr=0x30249c00, indim=16777728, inadr=0x301c9c00)
    at /Users/davem/projects/devkitpro/pacman-packages/citro3d/src/citro3d-1.7.1/source/renderqueue.c:395
#5  C3D_SyncDisplayTransfer (inadr=0x301c9c00, indim=16777728, outadr=0x30249c00, outdim=16777728, flags=3)
    at /Users/davem/projects/devkitpro/pacman-packages/citro3d/src/citro3d-1.7.1/source/renderqueue.c:425
#6  0x0012c410 in N3DS_UpdateRects.part.0 ()
#7  0x0012c504 in N3DS_FlipHWSurface ()
```
[3ds-sdl source](https://github.com/devkitPro/SDL/blob/fc1b44d02929fab4fabe01e217e7cdfe2e371eb0/src/video/n3ds/SDL_n3dsvideo.c#L495-L644)
flip calls drawbuffers and that signals the video thread.
```text
#8  0x00107e20 in Video::flip (this=this@entry=0x19a51c <video>, mspf=<optimized out>, paletteEffects=paletteEffects@entry=0x83459e8,
    effectsStopped=effectsStopped@entry=false) at /home/carsten/projects/openjazz/src/io/gfx/video.cpp:698
#9  0x0010b124 in loop (type=type@entry=NORMAL_LOOP, paletteEffects=0x83459e8, effectsStopped=effectsStopped@entry=false)
    at /home/carsten/projects/openjazz/src/main.cpp:513
#10 0x00118eb4 in JJ1DemoLevel::play (this=0x81c1260) at /home/carsten/projects/openjazz/src/jj1/level/jj1demolevel.cpp:126
#11 0x001021b0 in Game::playLevel (this=this@entry=0x817c2e0, fileName=fileName@entry=0x8241210 "MACRO.3", intro=intro@entry=false,
    checkpoint=checkpoint@entry=false) at /home/carsten/projects/openjazz/src/game/game.cpp:200
#12 0x001024c0 in Game::playLevel (this=this@entry=0x817c2e0, fileName=fileName@entry=0x8241210 "MACRO.3")
    at /home/carsten/projects/openjazz/src/game/game.cpp:333
#13 0x0010da7c in MainMenu::main (this=this@entry=0x82bcc80) at /home/carsten/projects/openjazz/src/menu/mainmenu.cpp:392
#14 0x0010b29c in play () at /home/carsten/projects/openjazz/src/main.cpp:450
#15 0x0010b4f4 in main (argc=0, argv=0x8000000) at /home/carsten/projects/openjazz/src/main.cpp:616
```
